/*
 * This source file was generated by the Gradle 'init' task
 */
package org.run;

import java.util.List;

import org.archivos.FlujoCaracteres;

public class App 
{
    public static void main(String[] args) 
    {
        FlujoCaracteres.path();
        String[] data = 
        {
            "parrafo 9\n",
            "parrafo 10\nparrafo 11\n",
            "parrafo 12:)\n"
        };
        FlujoCaracteres.writeEndByLine("flujo-caracteres", data);
        List<String> value = FlujoCaracteres.readByLine("flujo-caracteres");
        
        value.forEach(System.out::print);
    }
}
