/*
 * This source file was generated by the Gradle 'init' task
 */
package org.run;

import java.util.List;

import org.archivos.FlujoCaracteres;

public class App 
{
    public static void main(String[] args) 
    {
        FlujoCaracteres.path();
        String[] data = {
            "parrafo 1\n",
            "parrafo 2\nparrafo 3\n",
            "parrafo 4:)\n"
        };
        FlujoCaracteres.writeEnd("flujo-caracteres", data);
        List<String> value = FlujoCaracteres.read("flujo-caracteres");
        
        value.forEach(System.out::print);
    }
}
