/*
 * This source file was generated by the Gradle 'init' task
 */
package org.run;

import org.test.TestFlujoBytes;

public class App 
{
    public static void main(String[] args) 
    {
        // TestFlujoCaracteres.exec();
        TestFlujoBytes.exec();
    }
}
